export type SpriteTypes =
  | 'icon-heart'
  | 'icon-profile'
  | 'icon-search'
  | 'icon-cart'
  | 'icon-burger'
  | 'icon-logo'
  | 'icon-arrow'
  | 'icon-facebook'
  | 'icon-instagram'
  | 'icon-x-alt'
  | 'icon-crystal'
  | 'icon-google'
  | 'icon-check'
  | string
