import type { Metadata } from 'next'

import Providers from '@/providers/Providers'
import { Cormorant, Manrope } from 'next/font/google'

import RootHead from '@/components/helpers/RootHead'

import './globals.css'

const CormorantFont = Cormorant({
  variable: '--font-cormorant',
  weight: ['500', '600', '400'],
  subsets: ['latin']
})

const ManropeFont = Manrope({
  variable: '--font-manrope',
  weight: ['400', '500', '600'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <RootHead />
      <body
        className={`${ManropeFont.className} ${CormorantFont.variable} font-manrope text-black
          antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
